# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = b'\xe4\xf0\xa9*\xb2\xff@\xaf\xc0\x8a\x96C>\x11\x87\xf4'

_lr_action_items = {'SET': ([2, ], [13, ]), 'ID': (
    [0, 1, 2, 3, 4, 5, 6, 7, 9, 10, 11, 12, 13, 14, 15, 17, 18, 19, 21, 25, 26,
     27,
     28, 31, 33, ],
    [9, -2, 15, -3, -10, -5, -9, -1, -13, -4, -12, -11, 19, -17, 9, 9, 23, 9,
     -16,
     -6, 28, -19, 28, 9, -18, ]), '$end': (
    [1, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 14, 21, 25, 27, 33, ],
    [-2, -3, -10, -5, -9, -1, 0, -13, -4, -12, -11, -17, -16, -6, -19, -18, ]),
                    'LPAREN': (
                        [0, 1, 2, 3, 4, 5, 6, 7, 9, 10, 11, 12, 14, 15, 17, 19,
                         21,
                         23, 25, 27, 31, 33, ],
                        [2, -2, 2, -3, -10, -5, -9, -1, -13, -4, -12, -11, -17,
                         2,
                         2, 2, -16, 26, -6, -19, 2, -18, ]), 'FLOAT': (
    [0, 1, 2, 3, 4, 5, 6, 7, 9, 10, 11, 12, 14, 15, 17, 19, 21, 25, 27, 31,
     33, ],
    [11, -2, 11, -3, -10, -5, -9, -1, -13, -4, -12, -11, -17, 11, 11, 11, -16,
     -6,
     -19, 11, -18, ]), 'STRING': (
    [0, 1, 2, 3, 4, 5, 6, 7, 9, 10, 11, 12, 14, 15, 17, 19, 21, 25, 27, 31,
     33, ],
    [4, -2, 4, -3, -10, -5, -9, -1, -13, -4, -12, -11, -17, 4, 4, 4, -16, -6,
     -19,
     4, -18, ]), 'BOOL': (
    [0, 1, 2, 3, 4, 5, 6, 7, 9, 10, 11, 12, 14, 15, 17, 19, 21, 25, 27, 31,
     33, ],
    [6, -2, 6, -3, -10, -5, -9, -1, -13, -4, -12, -11, -17, 6, 6, 6, -16, -6,
     -19,
     6, -18, ]), 'INT': (
    [0, 1, 2, 3, 4, 5, 6, 7, 9, 10, 11, 12, 14, 15, 17, 19, 21, 25, 27, 31,
     33, ],
    [12, -2, 12, -3, -10, -5, -9, -1, -13, -4, -12, -11, -17, 12, 12, 12, -16,
     -6,
     -19, 12, -18, ]), 'DEFUN': ([2, ], [18, ]), 'RPAREN': (
    [1, 2, 3, 4, 5, 6, 7, 9, 10, 11, 12, 14, 15, 16, 17, 20, 21, 22, 24, 25, 27,
     28,
     29, 30, 32, 33, ],
    [-2, 14, -3, -10, -5, -9, -1, -13, -4, -12, -11, -17, -13, 21, -14, 25, -16,
     -15, 27, -6, -19, -7, 31, -8, 33, -18, ]), }

_lr_action = {}
for _k, _v in _lr_action_items.items():
    for _x, _y in zip(_v[0], _v[1]):
        if not _x in _lr_action:  _lr_action[_x] = {}
        _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'exprseq': ([2, 15, 17, 31, ], [16, 20, 22, 32, ]),
                  'defun': ([0, 2, 15, 17, 19, 31, ], [1, 1, 1, 1, 1, 1, ]),
                  'expr': ([0, 2, 15, 17, 19, 31, ], [8, 17, 17, 17, 24, 17, ]),
                  'set': ([0, 2, 15, 17, 19, 31, ], [3, 3, 3, 3, 3, 3, ]),
                  'list': ([0, 2, 15, 17, 19, 31, ], [5, 5, 5, 5, 5, 5, ]),
                  'atom': ([0, 2, 15, 17, 19, 31, ], [7, 7, 7, 7, 7, 7, ]),
                  'ids': ([26, 28, ], [29, 30, ]), 'func_call': (
    [0, 2, 15, 17, 19, 31, ], [10, 10, 10, 10, 10, 10, ]), }

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
    for _x, _y in zip(_v[0], _v[1]):
        if not _x in _lr_goto: _lr_goto[_x] = {}
        _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
    ("S' -> expr", "S'", 1, None, None, None),
    ('expr -> atom', 'expr', 1, 'p_expr',
     '/home/users/dan/projects/software/sandbox/lispy/parser/parser.py', 158),
    ('expr -> defun', 'expr', 1, 'p_expr',
     '/home/users/dan/projects/software/sandbox/lispy/parser/parser.py', 159),
    ('expr -> set', 'expr', 1, 'p_expr',
     '/home/users/dan/projects/software/sandbox/lispy/parser/parser.py', 160),
    ('expr -> func_call', 'expr', 1, 'p_expr',
     '/home/users/dan/projects/software/sandbox/lispy/parser/parser.py', 161),
    ('expr -> list', 'expr', 1, 'p_expr',
     '/home/users/dan/projects/software/sandbox/lispy/parser/parser.py', 162),
    ('func_call -> LPAREN ID exprseq RPAREN', 'func_call', 4, 'p_func_call',
     '/home/users/dan/projects/software/sandbox/lispy/parser/parser.py', 168),
    ('ids -> ID', 'ids', 1, 'p_ids',
     '/home/users/dan/projects/software/sandbox/lispy/parser/parser.py', 174),
    ('ids -> ID ids', 'ids', 2, 'p_ids',
     '/home/users/dan/projects/software/sandbox/lispy/parser/parser.py', 175),
    ('atom -> BOOL', 'atom', 1, 'p_atom',
     '/home/users/dan/projects/software/sandbox/lispy/parser/parser.py', 184),
    ('atom -> STRING', 'atom', 1, 'p_atom',
     '/home/users/dan/projects/software/sandbox/lispy/parser/parser.py', 185),
    ('atom -> INT', 'atom', 1, 'p_atom',
     '/home/users/dan/projects/software/sandbox/lispy/parser/parser.py', 186),
    ('atom -> FLOAT', 'atom', 1, 'p_atom',
     '/home/users/dan/projects/software/sandbox/lispy/parser/parser.py', 187),
    ('atom -> ID', 'atom', 1, 'p_atom',
     '/home/users/dan/projects/software/sandbox/lispy/parser/parser.py', 188),
    ('exprseq -> expr', 'exprseq', 1, 'p_exprseq',
     '/home/users/dan/projects/software/sandbox/lispy/parser/parser.py', 194),
    ('exprseq -> expr exprseq', 'exprseq', 2, 'p_exprseq',
     '/home/users/dan/projects/software/sandbox/lispy/parser/parser.py', 195),
    ('list -> LPAREN exprseq RPAREN', 'list', 3, 'p_list',
     '/home/users/dan/projects/software/sandbox/lispy/parser/parser.py', 204),
    ('list -> LPAREN RPAREN', 'list', 2, 'p_list',
     '/home/users/dan/projects/software/sandbox/lispy/parser/parser.py', 205),
    ('defun -> LPAREN DEFUN ID LPAREN ids RPAREN exprseq RPAREN', 'defun', 8,
     'p_defun',
     '/home/users/dan/projects/software/sandbox/lispy/parser/parser.py', 214),
    ('set -> LPAREN SET ID expr RPAREN', 'set', 5, 'p_set',
     '/home/users/dan/projects/software/sandbox/lispy/parser/parser.py', 220),
]
